package enumgen

// Package enumgen provides implementation for a type-safe enum definition base on github.com/akishichinibu/goenum/example
// Code generated by goenum 0.0.1. DO NOT EDIT.

type EnumHTTPSuccessVariant interface {
	_enum_2ff0489a1ee11b3b5d8f05a4a65734db()
	Equal(other EnumHTTPSuccessVariant) bool
	Match(Ok200 func(EnumHTTPSuccessVariantOk200), Created201 func(EnumHTTPSuccessVariantCreated201), Accepted202 func(EnumHTTPSuccessVariantAccepted202), NoContent204 func(EnumHTTPSuccessVariantNoContent204), PartialContent206 func(EnumHTTPSuccessVariantPartialContent206), BadRequest400 func(EnumHTTPSuccessVariantBadRequest400))
}

// the interface for variant Ok200

type EnumHTTPSuccessVariantOk200 interface {
	_enum_2ff0489a1ee11b3b5d8f05a4a65734db()
}

// the implementation struct for variant Ok200

type _EnumHTTPSuccessVariantOk200 struct{}

// the getters for variant Ok200

func (v *_EnumHTTPSuccessVariantOk200) _enum_2ff0489a1ee11b3b5d8f05a4a65734db() {}

// the Equal method for variant Ok200

func (v *_EnumHTTPSuccessVariantOk200) Equal(other EnumHTTPSuccessVariant) bool {
	if v == nil || other == nil {
		return false
	}
	otherImpl, ok := other.(*_EnumHTTPSuccessVariantOk200)
	if !ok {
		return false
	}
	return *v == *otherImpl
}

// the Match method for variant Ok200

func (v *_EnumHTTPSuccessVariantOk200) Match(Ok200 func(EnumHTTPSuccessVariantOk200), Created201 func(EnumHTTPSuccessVariantCreated201), Accepted202 func(EnumHTTPSuccessVariantAccepted202), NoContent204 func(EnumHTTPSuccessVariantNoContent204), PartialContent206 func(EnumHTTPSuccessVariantPartialContent206), BadRequest400 func(EnumHTTPSuccessVariantBadRequest400)) {
	Ok200(v)
}

// the Value method for variant Ok200

func (v *_EnumHTTPSuccessVariantOk200) Value() int {
	return 200
}

// the interface for variant Created201

type EnumHTTPSuccessVariantCreated201 interface {
	_enum_2ff0489a1ee11b3b5d8f05a4a65734db()
}

// the implementation struct for variant Created201

type _EnumHTTPSuccessVariantCreated201 struct{}

// the getters for variant Created201

func (v *_EnumHTTPSuccessVariantCreated201) _enum_2ff0489a1ee11b3b5d8f05a4a65734db() {}

// the Equal method for variant Created201

func (v *_EnumHTTPSuccessVariantCreated201) Equal(other EnumHTTPSuccessVariant) bool {
	if v == nil || other == nil {
		return false
	}
	otherImpl, ok := other.(*_EnumHTTPSuccessVariantCreated201)
	if !ok {
		return false
	}
	return *v == *otherImpl
}

// the Match method for variant Created201

func (v *_EnumHTTPSuccessVariantCreated201) Match(Ok200 func(EnumHTTPSuccessVariantOk200), Created201 func(EnumHTTPSuccessVariantCreated201), Accepted202 func(EnumHTTPSuccessVariantAccepted202), NoContent204 func(EnumHTTPSuccessVariantNoContent204), PartialContent206 func(EnumHTTPSuccessVariantPartialContent206), BadRequest400 func(EnumHTTPSuccessVariantBadRequest400)) {
	Created201(v)
}

// the Value method for variant Created201

func (v *_EnumHTTPSuccessVariantCreated201) Value() int {
	return 201
}

// the interface for variant Accepted202

type EnumHTTPSuccessVariantAccepted202 interface {
	_enum_2ff0489a1ee11b3b5d8f05a4a65734db()
}

// the implementation struct for variant Accepted202

type _EnumHTTPSuccessVariantAccepted202 struct{}

// the getters for variant Accepted202

func (v *_EnumHTTPSuccessVariantAccepted202) _enum_2ff0489a1ee11b3b5d8f05a4a65734db() {}

// the Equal method for variant Accepted202

func (v *_EnumHTTPSuccessVariantAccepted202) Equal(other EnumHTTPSuccessVariant) bool {
	if v == nil || other == nil {
		return false
	}
	otherImpl, ok := other.(*_EnumHTTPSuccessVariantAccepted202)
	if !ok {
		return false
	}
	return *v == *otherImpl
}

// the Match method for variant Accepted202

func (v *_EnumHTTPSuccessVariantAccepted202) Match(Ok200 func(EnumHTTPSuccessVariantOk200), Created201 func(EnumHTTPSuccessVariantCreated201), Accepted202 func(EnumHTTPSuccessVariantAccepted202), NoContent204 func(EnumHTTPSuccessVariantNoContent204), PartialContent206 func(EnumHTTPSuccessVariantPartialContent206), BadRequest400 func(EnumHTTPSuccessVariantBadRequest400)) {
	Accepted202(v)
}

// the Value method for variant Accepted202

func (v *_EnumHTTPSuccessVariantAccepted202) Value() int {
	return 202
}

// the interface for variant NoContent204

type EnumHTTPSuccessVariantNoContent204 interface {
	_enum_2ff0489a1ee11b3b5d8f05a4a65734db()
}

// the implementation struct for variant NoContent204

type _EnumHTTPSuccessVariantNoContent204 struct{}

// the getters for variant NoContent204

func (v *_EnumHTTPSuccessVariantNoContent204) _enum_2ff0489a1ee11b3b5d8f05a4a65734db() {}

// the Equal method for variant NoContent204

func (v *_EnumHTTPSuccessVariantNoContent204) Equal(other EnumHTTPSuccessVariant) bool {
	if v == nil || other == nil {
		return false
	}
	otherImpl, ok := other.(*_EnumHTTPSuccessVariantNoContent204)
	if !ok {
		return false
	}
	return *v == *otherImpl
}

// the Match method for variant NoContent204

func (v *_EnumHTTPSuccessVariantNoContent204) Match(Ok200 func(EnumHTTPSuccessVariantOk200), Created201 func(EnumHTTPSuccessVariantCreated201), Accepted202 func(EnumHTTPSuccessVariantAccepted202), NoContent204 func(EnumHTTPSuccessVariantNoContent204), PartialContent206 func(EnumHTTPSuccessVariantPartialContent206), BadRequest400 func(EnumHTTPSuccessVariantBadRequest400)) {
	NoContent204(v)
}

// the Value method for variant NoContent204

func (v *_EnumHTTPSuccessVariantNoContent204) Value() int {
	return 204
}

// the interface for variant PartialContent206

type EnumHTTPSuccessVariantPartialContent206 interface {
	_enum_2ff0489a1ee11b3b5d8f05a4a65734db()
}

// the implementation struct for variant PartialContent206

type _EnumHTTPSuccessVariantPartialContent206 struct{}

// the getters for variant PartialContent206

func (v *_EnumHTTPSuccessVariantPartialContent206) _enum_2ff0489a1ee11b3b5d8f05a4a65734db() {}

// the Equal method for variant PartialContent206

func (v *_EnumHTTPSuccessVariantPartialContent206) Equal(other EnumHTTPSuccessVariant) bool {
	if v == nil || other == nil {
		return false
	}
	otherImpl, ok := other.(*_EnumHTTPSuccessVariantPartialContent206)
	if !ok {
		return false
	}
	return *v == *otherImpl
}

// the Match method for variant PartialContent206

func (v *_EnumHTTPSuccessVariantPartialContent206) Match(Ok200 func(EnumHTTPSuccessVariantOk200), Created201 func(EnumHTTPSuccessVariantCreated201), Accepted202 func(EnumHTTPSuccessVariantAccepted202), NoContent204 func(EnumHTTPSuccessVariantNoContent204), PartialContent206 func(EnumHTTPSuccessVariantPartialContent206), BadRequest400 func(EnumHTTPSuccessVariantBadRequest400)) {
	PartialContent206(v)
}

// the Value method for variant PartialContent206

func (v *_EnumHTTPSuccessVariantPartialContent206) Value() int {
	return 206
}

// the interface for variant BadRequest400

type EnumHTTPSuccessVariantBadRequest400 interface {
	_enum_2ff0489a1ee11b3b5d8f05a4a65734db()
}

// the implementation struct for variant BadRequest400

type _EnumHTTPSuccessVariantBadRequest400 struct{}

// the getters for variant BadRequest400

func (v *_EnumHTTPSuccessVariantBadRequest400) _enum_2ff0489a1ee11b3b5d8f05a4a65734db() {}

// the Equal method for variant BadRequest400

func (v *_EnumHTTPSuccessVariantBadRequest400) Equal(other EnumHTTPSuccessVariant) bool {
	if v == nil || other == nil {
		return false
	}
	otherImpl, ok := other.(*_EnumHTTPSuccessVariantBadRequest400)
	if !ok {
		return false
	}
	return *v == *otherImpl
}

// the Match method for variant BadRequest400

func (v *_EnumHTTPSuccessVariantBadRequest400) Match(Ok200 func(EnumHTTPSuccessVariantOk200), Created201 func(EnumHTTPSuccessVariantCreated201), Accepted202 func(EnumHTTPSuccessVariantAccepted202), NoContent204 func(EnumHTTPSuccessVariantNoContent204), PartialContent206 func(EnumHTTPSuccessVariantPartialContent206), BadRequest400 func(EnumHTTPSuccessVariantBadRequest400)) {
	BadRequest400(v)
}

// the Value method for variant BadRequest400

func (v *_EnumHTTPSuccessVariantBadRequest400) Value() int {
	return 400
}

// the builder interface for EnumHTTPSuccessVariant

type EnumHTTPSuccessBuilder interface {
	Ok200() EnumHTTPSuccessVariant

	Created201() EnumHTTPSuccessVariant

	Accepted202() EnumHTTPSuccessVariant

	NoContent204() EnumHTTPSuccessVariant

	PartialContent206() EnumHTTPSuccessVariant

	BadRequest400() EnumHTTPSuccessVariant
}

// the builder for EnumHTTPSuccessBuilder

type enumHTTPSuccessBuilder struct{}

// the builder method for EnumHTTPSuccessVariantOk200Builder

func (enumHTTPSuccessBuilder) Ok200() EnumHTTPSuccessVariant {
	return &_EnumHTTPSuccessVariantOk200{}
}

// the builder method for EnumHTTPSuccessVariantCreated201Builder

func (enumHTTPSuccessBuilder) Created201() EnumHTTPSuccessVariant {
	return &_EnumHTTPSuccessVariantCreated201{}
}

// the builder method for EnumHTTPSuccessVariantAccepted202Builder

func (enumHTTPSuccessBuilder) Accepted202() EnumHTTPSuccessVariant {
	return &_EnumHTTPSuccessVariantAccepted202{}
}

// the builder method for EnumHTTPSuccessVariantNoContent204Builder

func (enumHTTPSuccessBuilder) NoContent204() EnumHTTPSuccessVariant {
	return &_EnumHTTPSuccessVariantNoContent204{}
}

// the builder method for EnumHTTPSuccessVariantPartialContent206Builder

func (enumHTTPSuccessBuilder) PartialContent206() EnumHTTPSuccessVariant {
	return &_EnumHTTPSuccessVariantPartialContent206{}
}

// the builder method for EnumHTTPSuccessVariantBadRequest400Builder

func (enumHTTPSuccessBuilder) BadRequest400() EnumHTTPSuccessVariant {
	return &_EnumHTTPSuccessVariantBadRequest400{}
}

// the singleton instance for EnumHTTPSuccess

var EnumHTTPSuccess EnumHTTPSuccessBuilder = &enumHTTPSuccessBuilder{}
