package enum

import enumgen "github.com/akishichinibu/goenum/example/internal/enumgen"

// This file provides the exported interface from enumgen
// Code generated by goenum 0.0.1. DO NOT EDIT.

type EnumColorVariant = enumgen.EnumColorVariant

type EnumColorBuilder = enumgen.EnumColorBuilder

type EnumColorVariantGray = enumgen.EnumColorVariantGray

type EnumColorVariantMix = enumgen.EnumColorVariantMix

type EnumColorVariantRed = enumgen.EnumColorVariantRed

var EnumColor = enumgen.EnumColor
