package enum

import enumgen "github.com/akishichinibu/goenum/example/internal/enumgen"

// This file provides the exported interface from enumgen
// Code generated by goenum 0.0.1. DO NOT EDIT.

type EnumHTTPSuccessVariant = enumgen.EnumHTTPSuccessVariant

type EnumHTTPSuccessBuilder = enumgen.EnumHTTPSuccessBuilder

type EnumHTTPSuccessVariantOk200 = enumgen.EnumHTTPSuccessVariantOk200

type EnumHTTPSuccessVariantCreated201 = enumgen.EnumHTTPSuccessVariantCreated201

type EnumHTTPSuccessVariantAccepted202 = enumgen.EnumHTTPSuccessVariantAccepted202

type EnumHTTPSuccessVariantNoContent204 = enumgen.EnumHTTPSuccessVariantNoContent204

type EnumHTTPSuccessVariantPartialContent206 = enumgen.EnumHTTPSuccessVariantPartialContent206

type EnumHTTPSuccessVariantBadRequest400 = enumgen.EnumHTTPSuccessVariantBadRequest400

var EnumHTTPSuccess = enumgen.EnumHTTPSuccess
